spring:
  sql.init.platform: org.hibernate.dialect.MariaDB103Dialect
  application:
    name: cli-service
  datasource:
    url: jdbc:mariadb://localhost:3310/onboard
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  main:
    allow-bean-definition-overriding: true